apiVersion: apps/v1
kind: Deployment
metadata:
  name: demotest
spec:
  selector:
    matchLabels:
      app: demotest
  replicas: 3
  template:
    metadata:
      labels:
        app: demotest
    spec:
      volumes:
        - name: appsettings
          configMap:
            name: appsettings
      containers:
      - name: demotest
        image: gsw/demotest:v1.0.0
        imagePullPolicy: IfNotPresent #从本地镜像里拉取
        ports:
        - containerPort: 82
        volumeMounts:
          - name: appsettings
            mountPath: /app/configuration
            readOnly: true