apiVersion: v1
kind: Service
metadata:
  name: demotest-service
  labels:
    app: demotest-service
spec:
  selector:
    app: demotest
  type: NodePort  #用主机IP:32100访问
  ports:
    - name: default
      nodePort: 32100 #用主机IP:32100访问
      protocol: TCP
      port: 82
      targetPort: 82