apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo01
spec:
  selector:
    matchLabels:
      app: demo01
  replicas: 3
  template:
    metadata:
      labels:
        app: demo01
    spec:
      volumes:
        - name: appsettings
          configMap:
            name: appsettings
      containers:
      - name: demo01
        image: gsw/demo01:v1.0.0
        imagePullPolicy: IfNotPresent #从本地镜像里拉取
        ports:
        - containerPort: 80
        volumeMounts:
          - name: appsettings
            mountPath: /configuration
            readOnly: true
