Logging: 
  LogLevel: 
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
AllowedHosts: "*"
ConnectionStrings: 
  Postgre: "Server=192.168.0.8;Port=5432;UserId=postgres;Password=postgres2018;Database=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=100;CommandTimeout=300;"